---
- name: Configure machine and launch app
  hosts: managed
  remote_user: ec2-user

  vars_prompt:
    - name: trello_api_key
      prompt: Enter trello api key immediately
    - name: trello_api_token
      prompt: Enter trello api token immediately

  tasks:
  - name: Install git and python
    become: yes
    ansible.builtin.yum:
      name:
        - git
        - python3
  - name: Ensure poetry installed
    ansible.builtin.shell:
      cmd: install_poetry.sh
      creates: .local/share/pypoetry/venv/bin/poetry
  - name: Ensure project directory exists with correct permissions
    become: yes
    ansible.builtin.file:
      path: /opt/todo_app
      state: directory
      owner: ec2-user
  - name: Checkout latest app code
    ansible.builtin.git:
      repo: 'https://github.com/arfacamble/DevOps-Course-Starter.git'
      dest: /opt/todo_app
      version: master
  - name: Poetry install
    ansible.builtin.shell:
      cmd: (cd /opt/todo_app && poetry=$(which poetry) && $poetry install)
  - name: create .env file
    ansible.builtin.template:
      src: .env.j2
      dest: /opt/todo_app/.env
  - name: create app service
    become: yes
    ansible.builtin.copy:
      src: todoapp.service
      dest: /etc/systemd/system/todoapp.service
  - name: launch app
    become: yes
    ansible.builtin.systemd:
      name: todoapp
      daemon_reload: true
      state: "restarted"
